# File: .github/workflows/repo-sync.yml
name: sync-JDRouter -Push
on:
  schedule:
    - cron: '1 0,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ main ]
  repository_dispatch:
    types: sync- JDRouter -Push
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #af97f0f12745a08dc156f7bcbe081dad6aca2020
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync  sync-JDRouter -Push
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/leifengwl/JDRouterPush.git"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.PAT }}
